const UPSERT_POSTS = 'UPSERT_POSTS';
const SET_LOGGED_IN = 'UPSERT_DEVICE_REGISTERED';
const SHOW_MODAL_COVER = 'SHOW_MODAL_COVER';
const HIDE_MODAL_COVER = 'HIDE_MODAL_COVER';
const SHOW_LOGIN_POPOVER = 'SHOW_LOGIN_POPOVER';
const HIDE_LOGIN_POPOVER = 'HIDE_LOGIN_POPOVER';
const SHOW_CONNECTING_LOGIN_POPOVER = 'SHOW_CONNECTING_LOGIN_POPOVER';
const UPSERT_USER_ENTITIES = 'UPSERT_USER_ENTITIES';
const LOGOUT_USER = 'LOGOUT_USER';
const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
const UPSERT_USER_PROFILE_ENTITIES = 'UPSERT_USER_PROFILE_ENTITIES';
const UPSERT_LINK_ENTITIES = 'UPSERT_LINK_ENTITIES';
const UPSERT_VIDEO_ENTITIES = 'UPSERT_VIDEO_ENTITIES';
const UPSERT_VIDEO_STAT_ENTITIES = 'UPSERT_VIDEO_STAT_ENTITIES';
const UPSERT_REPLY_DETAIL_ENTITIES = 'UPSERT_REPLY_DETAIL_ENTITIES';
const UPSERT_CURRENT_USER_REPLY_DETAIL_RELATION_ENTITIES = 'UPSERT_CURRENT_USER_REPLY_DETAIL_RELATION_ENTITIES';
const UPSERT_IMAGE_ENTITIES = 'UPSERT_IMAGE_ENTITIES';
const UPDATE_BALANCE = 'UPDATE_BALANCE';
const UPDATE_IS_PURCHASE = 'UPDATE_IS_PURCHASE';
const UPDATE_EXECUTE_TRANSACTION_STATUS = 'UPDATE_EXECUTE_TRANSACTION_STATUS';
const UPSERT_RECORDED_VIDEO = 'UPSERT_RECORDED_VIDEO';
const CLEAR_RECORDED_VIDEO = 'CLEAR_RECORDED_VIDEO';
const VIDEO_IN_PROCESSING = 'VIDEO_IN_PROCESSING';
const UPSERT_PROFILE_PICTURE = 'UPSERT_PROFILE_PICTURE';
const CLEAR_PROFILE_PICTURE = 'CLEAR_PROFILE_PICTURE';
const CLEAR_PUSH_NOTIFICATION = 'CLEAR_PUSH_NOTIFICATION';
const UPSERT_NOTIFICATION_UNREAD = 'UPSERT_NOTIFICATION_UNREAD';
const UPSERT_INVITE_CODE = 'UPSERT_INVITE_CODE';
const UPSERT_UNSEEN_REPLIES='UPSERT_UNSEEN_REPLIES';
const UPSERT_ALL_WHITELISTED='UPSERT_ALL_WHITELISTED';

export {
  UPSERT_POSTS,
  SET_LOGGED_IN,
  SHOW_MODAL_COVER,
  HIDE_MODAL_COVER,
  SHOW_LOGIN_POPOVER,
  SHOW_CONNECTING_LOGIN_POPOVER,
  HIDE_LOGIN_POPOVER,
  UPSERT_USER_ENTITIES,
  UPDATE_CURRENT_USER,
  UPSERT_USER_PROFILE_ENTITIES,
  UPSERT_REPLY_DETAIL_ENTITIES,
  UPSERT_CURRENT_USER_REPLY_DETAIL_RELATION_ENTITIES,
  UPSERT_LINK_ENTITIES,
  UPSERT_VIDEO_ENTITIES,
  UPSERT_VIDEO_STAT_ENTITIES,
  UPSERT_IMAGE_ENTITIES,
  UPDATE_BALANCE,
  UPDATE_IS_PURCHASE,
  UPDATE_EXECUTE_TRANSACTION_STATUS,
  UPSERT_RECORDED_VIDEO,
  CLEAR_RECORDED_VIDEO,
  LOGOUT_USER,
  VIDEO_IN_PROCESSING,
  UPSERT_PROFILE_PICTURE,
  CLEAR_PROFILE_PICTURE,
  CLEAR_PUSH_NOTIFICATION,
  UPSERT_NOTIFICATION_UNREAD,
  UPSERT_INVITE_CODE,
  UPSERT_UNSEEN_REPLIES,
  UPSERT_ALL_WHITELISTED
};
