const UPSERT_POSTS = 'UPSERT_POSTS';
const SET_LOGGED_IN = 'UPSERT_DEVICE_REGISTERED';
const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';
const UPSERT_USER_ENTITIES = 'UPSERT_USER_ENTITIES';
const ADD_USER_LIST = 'ADD_USER_LIST';

export { UPSERT_POSTS, SET_LOGGED_IN, SHOW_MODAL, HIDE_MODAL, UPSERT_USER_ENTITIES, ADD_USER_LIST };
