const UPSERT_POSTS = 'UPSERT_POSTS';
const SET_LOGGED_IN = 'UPSERT_DEVICE_REGISTERED';
const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';
const SHOW_TOAST = 'SHOW_TOAST';
const HIDE_TOAST = 'HIDE_TOAST';
const SHOW_MODAL_COVER = 'SHOW_MODAL_COVER';
const HIDE_MODAL_COVER = 'HIDE_MODAL_COVER';
const SHOW_LOGIN_POPOVER = 'SHOW_LOGIN_POPOVER';
const HIDE_LOGIN_POPOVER = 'HIDE_LOGIN_POPOVER';
const UPSERT_USER_ENTITIES = 'UPSERT_USER_ENTITIES';
const LOGOUT_USER = 'LOGOUT_USER';
const UPSERT_FEED_ENTITIES = 'UPSERT_FEED_ENTITIES';
const UPSERT_TRANSACTION_ENTITIES = 'UPSERT_TRANSACTION_ENTITIES';
const UPSERT_GIFFY_ENTITIES = 'UPSERT_GIFFY_ENTITIES';
const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
const UPSERT_TAG_ENTITIES = "UPSERT_TAG_ENTITIES";
const UPSERT_USER_PROFILE_ENTITIES = "UPSERT_USER_PROFILE_ENTITIES";
const UPSERT_USER_STAT_ENTITIES = "UPSERT_USER_STAT_ENTITIES";
const UPSERT_LINK_ENTITIES = "UPSERT_LINK_ENTITIES";
const UPSERT_VIDEO_ENTITIES = "UPSERT_VIDEO_ENTITIES";
const UPSERT_VIDEO_STAT_ENTITIES = "UPSERT_VIDEO_STAT_ENTITIES";
const UPSERT_HOME_FEED_ENTITIES = "UPSERT_HOME_FEED_ENTITIES";
const UPSERT_IMAGE_ENTITIES = "UPSERT_IMAGE_ENTITIES";
const UPDATE_BALANCE= "UPDATE_BALANCE";
const UPDATE_EXECUTE_TRANSACTION_STATUS = "UPDATE_EXECUTE_TRANSACTION_STATUS";
const UPSERT_VIDEO_CONTRIBUTION_ENTITIES = "UPSERT_VIDEO_CONTRIBUTION_ENTITIES" ;
const UPSERT_USER_CONTRIBUTION_ENTITIES = "UPSERT_USER_CONTRIBUTION_ENTITIES" ;
const UPDATE_PRICE_POINTS = "UPDATE_PRICE_POINTS";
const UPSERT_RECORDED_VIDEO = 'UPSERT_RECORDED_VIDEO';
const CLEAR_RECORDED_VIDEO = 'CLEAR_RECORDED_VIDEO';

export {
  UPSERT_POSTS,
  SET_LOGGED_IN,
  SHOW_MODAL,
  HIDE_MODAL,
  SHOW_TOAST,
  HIDE_TOAST,
  SHOW_MODAL_COVER,
  HIDE_MODAL_COVER,
  SHOW_LOGIN_POPOVER,
  HIDE_LOGIN_POPOVER,
  UPSERT_USER_ENTITIES,
  UPSERT_FEED_ENTITIES,
  UPDATE_CURRENT_USER,
  UPSERT_TRANSACTION_ENTITIES,
  UPSERT_GIFFY_ENTITIES,
  UPSERT_TAG_ENTITIES,
  UPSERT_USER_PROFILE_ENTITIES,
  UPSERT_USER_STAT_ENTITIES,
  UPSERT_LINK_ENTITIES,
  UPSERT_VIDEO_ENTITIES,
  UPSERT_VIDEO_STAT_ENTITIES,
  UPSERT_HOME_FEED_ENTITIES,
  UPSERT_IMAGE_ENTITIES,
  UPDATE_BALANCE,
  UPDATE_EXECUTE_TRANSACTION_STATUS,
  UPSERT_VIDEO_CONTRIBUTION_ENTITIES,
  UPSERT_USER_CONTRIBUTION_ENTITIES,
  UPDATE_PRICE_POINTS,
  UPSERT_RECORDED_VIDEO,
  CLEAR_RECORDED_VIDEO ,
  LOGOUT_USER
};
