# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pepo2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Pepo2
pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
end
